name: words_a_flutter_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_gl: ^0.0.21
  http: ^0.13.4
  three_dart: ^0.0.16
  three_dart_jsm: ^0.0.10
  webview_flutter: ^3.0.4
  google_fonts: ^3.0.1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
